### ISSUE TITLE
Public Storybook for UI Components

### ISSUE THREAD

**Issue by jason-riddle** [lyft/clutch#1066]
**Description**

Backstage has a publicly accessible storybook to browse components, https://backstage.io/storybook/?path=/story/plugins-examples--plugin-with-data. This makes it easy to browse components to get a better look and feel for each component. It would be great if Clutch had something similar.

Complexity [S/M/L]: M?

**Wireframes, Mockups, or Screenshots (if applicable)**

**Comment by danielhochman** [comment]
We launched a public storybook about a month ago available at https://storybook.clutch.sh/.

It's currently linked in the footer of the docs page https://clutch.sh. If you looked for it in a certain place, read some docs, etc and were surprised not to find it let us know. Either way we will take another pass at adding additional callouts and links throughout the docs so it's hopefully more discoverable.

Also if there's anything else you notice that's a bit off with our storybook, let us know!

**Comment by jason-riddle** [comment]
Ah, yes it is indeed in the footer.

As far as discoverability, it looks like there is one short sentence documenting it

<img width="2672" alt="Screen Shot 2021-02-24 at 10 31 46 AM" src="https://user-images.githubusercontent.com/2156866/109048162-9ce95080-768b-11eb-9da3-f0c523f7294c.png">

Could this be a sub-bullet under Frontend on the left side? Maybe Frontend -> Browse Available Components, or something like that.

**Comment by dschaller** [comment]
Opened #1387 - @jason-riddle let me know what you think about the layout of that
