### ISSUE TITLE
gateway: graceful shutdown

### ISSUE THREAD

**Issue by danielhochman** [lyft/clutch#12]
**Description**

The gateway should cancel contexts and wait for them to complete before shutting down on `SIGTERM`, etc. 

We have code in our private impl that we can provide for reference.

In the future, we will also want to send some kind of cleanup signal to services to allow them to gracefully shutdown. Probably filed as a separate issue once we fix this one, as it way require changes to the `service` constructor.

Complexity [S/M/L]: S

**Comment by gumpt** [comment]
I'd like to work on this next week. I think I know what private code you're referring to, and either wrote or modified it at some point. 😄
