### ISSUE TITLE
audit: non-persistent or local persistence mode

### ISSUE THREAD

**Issue by danielhochman** [lyft/clutch#168]
**Description**

For testing or dev environments it could make sense not to rely on postgres and just do a direct flush to the sinks rather than the database first.

The other possibility is supporting an alternative to postgres for persistence, like a local sqlite. This would have the benefit of still working with the audit trail APIs when implemented to display trails in the UI.

From @pcn
> That audit example seems to rely on a postgres connection. Is there a lighter-weight test like a volume with a sqlite or something?
> https://lyftoss.slack.com/archives/C015UJ6LED9/p1596166250124600?thread_ts=1596142318.122700&cid=C015UJ6LED9

Complexity [S/M/L]: S

**Comment by gumpt** [comment]
I'd like to work on this over the next few days. I think the right way to do it is to change the configuration proto to have a `oneof` local or more database config.

I'd change documentation to make sure examples/getting started are updated to match the new config and suggest local-only as an easier starting point to be up and running.
