### ISSUE TITLE
api: move from protobuf.js fork to upstream

### ISSUE THREAD

**Issue by dschaller** [lyft/clutch#19]
**Description**

Clutch is currently using a [fork of protobufjs](https://github.com/natiz/protobuf.js#1d626f84db4a4f339004609f654a9f24a211b716) to generate the frontend api modules.

Ideally, Clutch would be using the upstream. Investigate what is required for this, upstream needed fixes, and move Clutch onto https://github.com/protobufjs/protobuf.js.

Complexity [S/M/L]: M

**Comment by danielhochman** [comment]
fixed by #243
