### ISSUE TITLE
Select Dropdown list items looks cluttered

### ISSUE THREAD

**Issue by tilakraj9560** [lyft/clutch#1960]
**Description**
Whenever select dropdown is used in conjunction with other elements, mostly with forms, it seems all the list items are cluttered in one row.
**Expected Behavior**
each list item should be present in a separate row.

**Actual Behavior**
![image](https://user-images.githubusercontent.com/73481431/149663987-7c6d519d-22e6-4a11-8f1e-d0706e6baf3e.png)

**Version**
Commit used 8th Jan 2022.

**Other Context**

**Comment by dschaller** [comment]
@tilakraj9560 can you provide a snippet of code where you're seeing this issue? I'm having a hard time reproducing.

This is the snippet of code I'm using:
```tsx
  <div>
    <form>
      <Select name="storybookDemo" {...props} />
    </form>
  </div>
```
