### ISSUE TITLE
The Error component isn't nested in the Feedback folder

### ISSUE THREAD

**Issue by jpeach** [lyft/clutch#2095]
**Description**

<img width="229" alt="Screen Shot 2022-03-09 at 5 11 47 pm" src="https://user-images.githubusercontent.com/9917/157383023-93064378-4c25-4e64-96ee-cadaf8f07418.png">

In the storybook screenshot above, the Error component is shown at the same level as the Feedback folder. In the actual source, Error is nested under the "Feedback" directory, but specifies "Core/Error" in its Meta export.

**Expected Behavior**

On-disk sources should roughly match the component hierarchy to make things easier to find.

This diff convinces storybook to move the component, but I'm not sure whether this has any other effects:
```
--- frontend/packages/core/src/Feedback/error/stories/error.stories.tsx
+++ frontend/packages/core/src/Feedback/error/stories/error.stories.tsx
@@ -6,7 +6,7 @@ import type { ErrorProps } from "../index";
 import Error from "../index";

 export default {
-  title: "Core/Error",
+  title: "Core/Feedback/Error",
   component: Error,
 } as Meta;
```

**Comment by smonero** [comment]
thanks for doing this! :)
