### ISSUE TITLE
Migrate from @material-ui to @mui

### ISSUE THREAD

**Issue by jpeach** [lyft/clutch#2097]
**Description**

Complexity [S/M/L]: L

Ref https://mui.com/blog/material-ui-is-now-mui/

The difference in naming is a bit confusing for newcomers, and the docs are all using `@mui`.

**Comment by jdslaugh** [comment]
Hi @jpeach

We've already started some work on this in the background so we'll update this ticket as progress continues.

Thanks for creating it!

Josh
