### ISSUE TITLE
ci: add a dependency management bot

### ISSUE THREAD

**Issue by dschaller** [lyft/clutch#25]
**Description**

Add a dependency management bot for frontend and backend packages.

One option could be to use [Dependabot](https://dependabot.com/) as it is owned by GitHub and might have better support/easier integration. Another popular tool is [Renovate](https://github.com/renovatebot/renovate).

Complexity [S/M/L]: S

**Comment by jarz** [comment]
@dschaller - don't know why my PR didn't link back to this issue

**Comment by jarz** [comment]
Looking around frontend code tonight - just saw a few more package.json files to add to dependabot.
