### ISSUE TITLE
tooling: hot reload for the backend

### ISSUE THREAD

**Issue by mcutalo88** [lyft/clutch#293]
**Description**

Develop or adopt hot reload functionality for the backend. Currently a popular option to adopt seems to be [air](https://github.com/cosmtrek/air).

Complexity [S/M/L]: S

**Wireframes, Mockups, or Screenshots (if applicable)**

**Comment by danielhochman** [comment]
https://github.com/lyft/clutch/pull/292 from @mcutalo88 fixed for core.

We should add to the scaffolded gateway as well though.

**Comment by mcutalo88** [comment]
forgot about the gateway, let me make a pr thanks @danielhochman.
