### ISSUE TITLE
frontend: enter doesn't submit form in MetadataTable

### ISSUE THREAD

**Issue by gkleiman** [lyft/clutch#364]
**Description**
Pressing return/enter while editing a form that's part of a `MetadataTable` doesn't submit the form, e.g., after updating the max size in the resize hpa workflow.

**Expected Behavior**
Pressing "enter" when a input component is focused should submit the form/move to the next step.

**Actual Behavior**
Nothing happens when "enter" is pressed.

**Version**
Current master

**Comment by dschaller** [comment]
closed in https://github.com/lyft/clutch/pull/442
