### ISSUE TITLE
Amiibo example file has import from "@clutch/core" instead of "@clutch-sh/core"

### ISSUE THREAD

**Issue by sbansal7** [lyft/clutch#384]
**Description**

After following the instructions to add example service to clutch, I get error:
```
clutch/frontend/workflows/amiibo/dist/hello-world.js
Module not found: Can't resolve '@clutch/core' in '/Users/sbansal/go/src/clutch/frontend/workflows/amiibo/dist'
```
**Expected Behavior**
There should not be error message, instead Amiibo service should show up on dashboard.
**Actual Behavior**

**Version**
Latest version with commit-id `36c6aed6697902f769435f5d521c8aa61eae3466`

**Other Context**
I found that in the committed code, there is import from "@clutch/core" instead of "@clutch-sh/core".
E.g. on this line and few subsequent lines: https://github.com/lyft/clutch/blob/main/examples/amiibo/frontend/workflows/amiibo/src/hello-world.tsx#L10

After I change that to use "@clutch-sh/core", it started working for me.

**Comment by scarlettperry** [comment]
HI @sbansal7, thank you for raising this! We fixed this in https://github.com/lyft/clutch/pull/422.
