### ISSUE TITLE
frontend: no vertical spacing around select control

### ISSUE THREAD

**Issue by Augustyniak** [lyft/clutch#411]
**Description**
There is no vertical spacing of any kind around `Select` control that's exported by clutch/core package.

**Expected Behavior**
Select control has vertical spacing that's similar to the spacing that's implemented by `TextField` from clutch/core.

**Actual Behavior**
See the difference between `TextField` and `Select` controls in the screenshot below
 
<img width="583" alt="Screen Shot 2020-09-15 at 9 01 09 AM" src="https://user-images.githubusercontent.com/4410346/93235146-0440c300-f732-11ea-9187-0d08967f0328.png">

**Version**
a184a1753a6ffda0875c4738f2480c0dec9c6438

**Comment by Augustyniak** [comment]
It's debatable whether it's a bug or a feature request - marking it as a bug for now. Feel free to change as needed.

**Comment by dschaller** [comment]
closed in https://github.com/lyft/clutch/pull/441
