### ISSUE TITLE
frontend: datetime pickers

### ISSUE THREAD

**Issue by Augustyniak** [lyft/clutch#414]
Add a datetime picker based off a [`KeyboardDateTimePicker ` from material-ui/pickers package](https://material-ui-pickers.dev/api/KeyboardDateTimePicker). [Material UI official docs](https://material-ui.com/components/pickers/#native-pickers) recommend the use of pickers from this package.

For now, the only way to ask user for a datetime with the use of controls exposed by clutch is to use a `TextField` which implements this functionality with the use of native controls.

```javascript
 <TextField type="datetime-local" />
```

This kind of works but has a few downsides:
* TextField exposes a selected date as a string which makes working with dates harder than necessary - a developer needs to find a way to convert them to `Date` objects before using them etc.
* It works best in Chrome, Chrome actually allow you to pick the date and the time with the use of nice UI.
* In Safari and Firefox (I have not tested other browsers), the only way for a user to provide date and time is to manually type it in the correct format (that's not obvious to the user).

| Chrome | Safari | Firefox |
| ----- | ----- | ------ |
| <img width="583" alt="Screen Shot 2020-09-15 at 5 16 58 PM" src="https://user-images.githubusercontent.com/4410346/93277705-5d7f1580-f777-11ea-99d5-51bd6a29c040.png"> | <img width="543" alt="Screen Shot 2020-09-15 at 5 17 16 PM" src="https://user-images.githubusercontent.com/4410346/93277718-6374f680-f777-11ea-916a-a45f41b517ae.png"> | <img width="548" alt="Screen Shot 2020-09-15 at 5 17 33 PM" src="https://user-images.githubusercontent.com/4410346/93277722-67087d80-f777-11ea-8da4-2573181ea8d3.png"> |

Complexity: M

**Comment by dschaller** [comment]
Closed in #2447
