### ISSUE TITLE
core: update node.js to 14.0

### ISSUE THREAD

**Issue by Augustyniak** [lyft/clutch#416]
Update node.js version to 14.0 to get access to option chaining [source](https://cri.dev/posts/2020-05-01-Optional-chaining-in-Node.js-14/#safe-property-access). Currently if one tries to use optional chaining in `clutch.config.js` the build files:

```javascript
const faults = e.scenario?.faults; // this fails
```

```
$ yarn workspace @clutch-sh/tools registerWorkflows $PWD/src
$ node workflow-registrar.js /home/runner/work/clutch-private/clutch-private/frontend/src
/home/runner/work/clutch-private/clutch-private/frontend/src/clutch.config.js:136
              const faults = e.scenario?.faults;
                                        ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
```

Complexity:
S

**Comment by danielhochman** [comment]
@dschaller any opposition to moving to 14 (is current release, LTS starts end of october).

also would need to add some documentation or tooling checks along with it since a lot of people will likely come in with older versions from their OS.

**Comment by dschaller** [comment]
@Augustyniak I'm hesitant to set the min node version to 14 until it's LTS. You should be able to achieve the same thing optional chaining provides with conditionals.

 Let me know if you have questions on how to do this

**Comment by Augustyniak** [comment]
@dschaller I was able to work around the lack of optional chaining in my PR - thanks for offering help tho. I opened this issue  mainly to surface "the issue" to wider audience since I think that we should eventually bump node.js's version here. It's fine by me if we decide to wait for LTS release first.

**Comment by Augustyniak** [comment]
Per https://github.com/nodejs/Release they are going to make node.js v14 an LTS starting on 2020-10-27.

**Comment by Augustyniak** [comment]
v14.0 became an active LTS today :) https://nodejs.org/en/about/releases/

**Comment by Augustyniak** [comment]
@dschaller I believe that this issue has been fixed already in https://github.com/lyft/clutch/pull/1342. Closing it.
