### ISSUE TITLE
docs: unhighlight duplicate line of code

### ISSUE THREAD

**Issue by scarlettperry** [lyft/clutch#449]
**Description**
In https://clutch.sh/docs/development/feature/#endpoints, `import "google/api/annotations.proto";` is highlighted as a new addition to the code snippet, but it is already included in https://clutch.sh/docs/development/feature/#boilerplate.

`import "google/api/annotations.proto";` should be unhighlighted in https://clutch.sh/docs/development/feature/#endpoints.

Complexity [S/M/L]: S

**Comment by nathanmkaya** [comment]
Hi, can I take this?

**Comment by scarlettperry** [comment]
Hi @nathanmkaya, yes! Let us know if you have any questions.
