### ISSUE TITLE
k8s: more meaningful error message

### ISSUE THREAD

**Issue by Augustyniak** [lyft/clutch#483]
**Description**

One of the errors returned from ListPods of `k8s` looks as follows:

<img width="735" alt="Napkin 09-28-20, 3 05 14 PM" src="https://user-images.githubusercontent.com/4410346/94491063-535c0e80-019c-11eb-8118-07483aac189f.png">

Notice that API group is an empty string in the error above. Apparently this translates to a core group - could we improve an error message so that it handles empty api groups better?

Complexity: S

**Comment by dschaller** [comment]
@Augustyniak I believe this was fixed as part of #1102 and #1120. Can you confirm if this is still an issue?

**Comment by mikecutalo** [comment]
Going to close out this issue, like @dschaller mentioned this should be resolved via the enhancements to error handling above.
