### ISSUE TITLE
k8s: Add support for k8s services

### ISSUE THREAD

**Issue by CSP197** [lyft/clutch#520]
**Description**

As a clutch user on k8s, I would like clutch to be able to describe a running k8s service and list the running k8s services in a namespace given its name and namespace as applicable.

There would need to be two workflows:

_DescribeService_
- Needs a service name, its clientset, and the namespace
- Returns a table of information that describes the service
- Similar to `kubectl describe service abc -n xyz`

_ListServices_
- Needs a clientset, and the namespace
- Returns a table of information that lists out the running services in the specified namespace
- Similar to `kubectl get services -n xyz`

Complexity [S/M/L]: S

**Wireframes, Mockups, or Screenshots (if applicable)**

**Comment by rithujohn191** [comment]
Thanks for reporting.

We will soon be adding a dashboard dedicated to K8s resources where a user will be able to get an overview of the k8s resources for their service running across all configured Kubernetes clusters. As a part of this effort, the `describe` and `get` actions you requested will be incorporated. We are currently working on a roadmap to deliver these features incrementally to the user. Will update this ticket with details once the timeline is finalized. In the meantime feel free to open up PRs with the API implementations of these features.

**Comment by caiorcferreira** [comment]
Any updates on the K8S dashboard? This would be an incredible addition!

Thanks

**Comment by rithujohn191** [comment]
The current K8s dashboard has support for a pods, deployments, stateful sets and cron tables

**Comment by rithujohn191** [comment]
This feature is now complete
