### ISSUE TITLE
Docs: Roadmap link 404s

### ISSUE THREAD

**Issue by Opswatch** [lyft/clutch#54]
**Description**
On https://clutch.sh/docs/about/what-is-clutch/ when clicking roadmap it goes to https://clutch.sh/docs/roadmap which 404s instead of https://clutch.sh/docs/about/roadmap

**Expected Behavior**
Get a page with the roadmap

**Comment by gumpt** [comment]
Thank you for reporting this! We have an open issue to track broken links more automatically (#9). Until then we're at the mercy of reporters like you! 😄
