### ISSUE TITLE
backend: observable retry library

### ISSUE THREAD

**Issue by mikecutalo** [lyft/clutch#790]
**Description**

Build a generic retry library, with a redeeming quality of being observable such as logging and stats. The motivation behind this issue is that client libraries such as the `aws-go-sdk` have retry-able functionality built in however its not possible observe these retries or why the client library is even retrying at all.

This retry library should implement all of the basic retry / backoff / jitter techniques, in a as enough of a generic way to use this throughout the codebase.

Complexity [S/M/L]: S

**Comment by goku321** [comment]
Is this open? I can try implementing this in coming weeks.

**Comment by mikecutalo** [comment]
Hey @goku321 yeah its open! I can assign you to the task, let us know if you have any questions!
