### ISSUE TITLE
docs: check for broken links

### ISSUE THREAD

**Issue by dschaller** [lyft/clutch#9]
**Description**

Add a CI job to check for broken links in the documentation.

Could look into using something like [broken-link-checker](https://www.npmjs.com/package/broken-link-checker) or [linkinator](https://github.com/JustinBeckwith/linkinator) from the generated preview site.

Complexity [S/M/L]: S

**Comment by danielhochman** [comment]
https://github.com/facebook/docusaurus/pull/3059 will help with this once it makes its way into a docusaurus release.
